//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimEngine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unsupported automata type")]
        public string UNSUPPORTED_TYPE {
            get {
                return ((string)(this["UNSUPPORTED_TYPE"]));
            }
            set {
                this["UNSUPPORTED_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Coordinates to big for game board")]
        public string COORDINATES_TOO_BIG {
            get {
                return ((string)(this["COORDINATES_TOO_BIG"]));
            }
            set {
                this["COORDINATES_TOO_BIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No coordinates specified in the file")]
        public string NO_COORDINATES {
            get {
                return ((string)(this["NO_COORDINATES"]));
            }
            set {
                this["NO_COORDINATES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The game board has an invalid width and or height")]
        public string INVALID_SIZE {
            get {
                return ((string)(this["INVALID_SIZE"]));
            }
            set {
                this["INVALID_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid row read, expected number to indicate a run")]
        public string INVALID_ROW {
            get {
                return ((string)(this["INVALID_ROW"]));
            }
            set {
                this["INVALID_ROW"] = value;
            }
        }
    }
}
